apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sux4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xahk-tenant/rhtap-demo-app/hacbs-test-project-sux4@sha256:ab4496cb57d82ba65e1def36803df143030c7ca5d1382ed27446207f46f8804a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
